### ISSUE TITLE
请问bot创建的机器root密码是多少呢？

### ISSUE THREAD

**Issue by Jakob-Boy** [zayabighead/digitalocean-helper-bot#1]
请问bot创建的机器root密码是多少呢？好像bot无法查询到

**Comment by realByg** [comment]
### **?**
![image](https://user-images.githubusercontent.com/39550067/130026496-9420601c-cfb3-47be-be56-dc0ce8a011fe.png)

**Comment by annkoxx** [comment]
> ### **?**
> ![image](https://user-images.githubusercontent.com/39550067/130026496-9420601c-cfb3-47be-be56-dc0ce8a011fe.png)

这个密码是错误的。不正确

**Comment by Jakob-Boy** [comment]
需要等待几分钟后才可以连接，查看源码可知，是通过登录root后修改得到的密码，并不是do创建后发送到邮箱的密码
